### ISSUE TITLE
issue with box shadow when site height is to small 

### ISSUE THREAD

**Issue by themedotal** [IainAndrew/footer-reveal#4]
issue with box shadow when site height is too small.

**Comment by IainAndrew** [comment]
All of the plugin's functionality is disabled when the window height is less than the footer height. If you want to have a box shadow regardless of the window height, you could apply a box shadow in your CSS that will be overridden by the plugin if the window height is greater than the footer height.

**Comment by themedotal** [comment]
Hi, there is another case when the content height is smaller than window height.

check the screenshot

![screenshot](https://s12.postimg.org/z4fhb2pz1/Screen_Shot_2016_12_01_at_14_24_14.png)

**Comment by IainAndrew** [comment]
That should be fixed now: 7a6e944198b5984b06b299c641c2f9bd4d808229
