### ISSUE TITLE
if footer height change 

### ISSUE THREAD

**Issue by themedotal** [IainAndrew/footer-reveal#5]
HI,

My issue is if the footer height change. For example when we have an toggle or accordion inside fotoer. Is any event or way to recalculate the footer height change after the toggle click?

**Comment by IainAndrew** [comment]
@themedotal I've added a 'footerRevealResize' event in 647fc5ea37adf9c2cf6b7dcfa6ba66a3a96374bc, so when your footer changes height (accordion toggle etc), call `$('footer').trigger('footerRevealResize');`
