### ISSUE TITLE
Incompatible with flexbox "sticky footer"

### ISSUE THREAD

**Issue by drywall** [IainAndrew/footer-reveal#7]
Recently decided to use this plugin on a site I'm building. I installed it and it appeared to be working great... until I realized the footer element wasn't receiving any mouse events. Couldn't trigger hover effects, click events, etc.

After some messing around I discovered that the problem lay in the fact that the flexbox approach I was using to make sure my page content ran as long as browser window was tall ( see https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/ ) was incompatible with this plugin. 

I don't know if a resolution is possible or not, but wanted to flag that these two things don't play well together.

**Comment by IainAndrew** [comment]
Hey, I think I've got a solution: 
Set the 'zIndex' property on your footerReveal instance to 0 (or anything higher than -1), and, in your css, set the z-index of your content to 1 (or anything higher than the value of your footerReveal's zIndex property).
Demo here - http://codepen.io/overflowhidden/pen/zZbjXY

Let me know if it works for you, and thanks for bringing it to my attention!

**Comment by drywall** [comment]
On my preliminary testing, that seems to have helped. Thanks!
